---
- name: implementing tag
  hosts: all
  tasks:
   - name: install tree
     apt:
      name: tree
      state: present
     tags: tree_installtion
   - name: creater user
     user:
      name: mani
      password: dillip
     tags: user_creation
   - name: copy/etc/passwd file
     copy:
      src: /etc/passwd
      dest: /tmp
...