---
- name: install jenkins s/with_items
  hosts: jenkinsserver
  tasks:
   - name: required software
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: openjdk-8-jdk,b: yes}
      - {a: git,b: no}
      - {a: maven,b: no}
   - name: Download jenkins.war
     get_url:
        url: https://get.jenkins.io/war-stable/2.332.2/jenkins.war
        dest: /home/ubuntu
   - name: start jenkins
     shell: java -jar jenkins.war
- name: install tomcat9 and required s/war
  host: server
  tasks: 
   - name: install tomcat9 and tomcat9-admin
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
     - {a: tomcat9,b: yes}
     - {a: tomcat9-admin,b: no}
- name: copy tomcat-users.xml file
  copy:
   src: tomcat-user.xml
   dest: /etc/tomcat9