---
- name: install jenkins s/with_items
  hosts: jenkins
  tasks:
   - name: required software
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a= openjdk-8-jdk,b= yes}
      - {a= git,b= no}
      - {a= maven,b= no}
...