---
- name: Error handlimg
  hosts: all
  tasks:
   - block:
      - name: install tomcat8
        apt:
         name: tomcat8
         state: present
         update_cache: yes
     rescue: 
      - name: install tomcat9
        apt:
         name: tomcat9
        state: present
        update_cache: yes
     always:
      - name: check the url response
        uri:
         url: "{{item}}"
         status_code: 200
        with_items:
         - http://172.31.87.212
         - http://172.31.80.220
         - http://172.31.18.43
...
      