---
- name: user creation using host scop variable
  hosts: 172.31.87.212
  tasks:
   - name: create user
     user:
      name: "{{a}}"
      password: "{{b}}"
      home: "{{c}}"
      uid: "{{d}}"
      shell: "{{e}}"
...